---
- name: consul_container
  ignore_errors: yes
  register: consul_container_fail
  become: true
  docker_container:
     name: consul
     image: progrium/consul
     ports:
       - 8300:8300
       - 8301:8301
       - 8301:8301/udp
       - 8302:8302
       - 8302:8302/udp
       - 8400:8400
       - 8500:8500
       - 53:8600/udp
     state: started
     command: "-server -bootstrap-expect 1 -advertise {{ ansible_eth0.ipv4.address }} "

- name: registrator
  ignore_errors: yes
  docker_container:
      name: registrator
      image: gliderlabs/registrator
      security_opts: "label:type:docker_t"
      volumes : 
         - "/var/run/docker.sock:/tmp/docker.sock:rw"
      state: started
      network_mode: host
      command:  "consul://localhost:8500"



- name: mount_directory
  become: true
  file:
     dest: "/mnt/templates/"
     recurse: true
     directory_mode: yes
     group: docker
     

- name: mounts_for_containers
  become: true
  copy:
     force: yes
     src: "{{ ansible_root }}/consul/files/service.ctmpl"
     dest: "/mnt/templates/service.ctmpl"
     group: docker
     mode: "777"

- name: consul-proxy
  become: true
  docker_container:
     ports:
        - 80:80
     image: jlordiales/nginx-consul
     restart: yes
     name: consul-proxy
     volumes: 
        - "/mnt/templates:/templates:rw"
     links:
        - consul:consul

#- name: ansible hack  -dns-port=8600 -recursor=8.8.8.8
#  command:  bash -c "yes | pip uninstall docker-py"
#  when: consul_container_fail|failed
#  become: True
#
#- name: ansible hack2
#  command: /usr/bin/pip install docker-py==1.9.0
#  when: consul_container_fail|failed
#  become: True
#
#- name: consul_container_again
#  when: consul_container_fail|failed
#  docker_container:
#     name: consul
#     image: consul
#     ports:
#       - 8300:8300
#       - 8301:8301
#       - 8301:8301/udp
#       - 8302:8302
#       - 8302:8302/udp
#       - 8400:8400
#       - 8500:8500
#       - 53:53/udp
#     state: started
#     command: "-server -dns-port=53 -recursor=8.8.8.8"
#

- name: kill connections to rerun ansible run
  shell: ps -aux |  awk /sshd/'{print $2}' | xargs kill -9
  when: consul_container_fail|failed
  become: yes
