---
- name: install packages
  package: name={{item}} state=latest
  with_items:
     - docker
     - vim
     - git
     - libselinux-python
     - bind-utils
     - cowsay
     - "@development-tools"
  become: true
- name: python packages
  pip: requirements=/vagrant/requirements.txt
  become: true
  
- name: get variables
  debug: var=hostvars[inventory_hostname]
